services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: web-workout:latest
    container_name: web-workout
    ports:
      - "5000:5000"
    volumes:
      - workout_db:/data
    environment:
      - FLASK_ENV=production
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - FLASK_SESSION=${FLASK_SESSION}
      - SERVER_NAME=${SERVER_NAME}
    restart: unless-stopped

volumes:
  workout_db:
